apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-stage-service
  labels:
    app: ilcittadinomb-stage
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: app  
    